POST http://127.0.0.1:5000/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
PUT http://127.0.0.1:5000/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjM3NjAwMjIwfQ.AUsYGg-N2eqvnxME8jD6f4xBuzeX7TFtxXxEesX8G6A"
}

###

#GET http://127.0.0.1:5000/movies/3
GET http://127.0.0.1:5000/directors/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjM3NjAwMjIwfQ.AUsYGg-N2eqvnxME8jD6f4xBuzeX7TFtxXxEesX8G6A

<> 2021-11-22T182201.200.json

###
DELETE http://127.0.0.1:5000/directors/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjM3NjAwMjIwfQ.AUsYGg-N2eqvnxME8jD6f4xBuzeX7TFtxXxEesX8G6A
